#cloud-config
users:
  - name: admi
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP3rGtT/FZ05ebIeCLdDZwr8tMiDzU7jC+iejMNlWWEk Admi@Ubuntu