---
- name: test
  gather_facts: false
  hosts: webservers
  become: yes
  vars:
    ansible_ssh_user: admi
    nginx_web_root: /var/www/html

  pre_tasks:
    - name: Validating the ssh port is open and
      wait_for:
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: 22
        delay: 5
        timeout: 300
        state: started
        search_regex: OpenSSH

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure web root exists
      ansible.builtin.file:
        path: "{{ nginx_web_root }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Remove default nginx index page (if present)
      ansible.builtin.file:
        path: "{{ nginx_web_root }}/index.nginx-debian.html"
        state: absent

    - name: Enable and start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
